language: python
python:
- '3.5'
- '3.6'
install:
- pip install .
- pip install coveralls
- pip install cryptography
- pip install aiohttp
script: coverage run --source pushbullet -m py.test
#deploy:
#  provider: pypi
#  user: randomchars
#  on:
#    tags: true
#    all_branches: true
#    python: '3.5'
#  distributions: sdist bdist_wheel
#  password:
#    secure: AF3VwPWZS4wDEuwhixbYJyF5jgWccAusPOq4ZdVOGzOmxAnc4DSuEr3sx6Z9HC3Svnw6nncbwx7nCCfrhX9va68xKiyNzkwa2jWnHWWKiYbGIY5oOsy728ElUA3cBg3fJWQy/+5wWdoS4a21jYw1MtqgVmMgEV3V3MvAy5nz98A=
after_success:
  coveralls
