language: python
python:
- '3.5'
- '3.6'
- '3.7'
dist: xenial
sudo: true

before_install:
  - "pip install -U pip"
  - "python setup.py install"

install:
- pip install .
- pip install coveralls
- pip install cryptography
- pip install requests
- pip install aiohttp
- pip install tqdm
- pip install python-magic

script: coverage run --source pushbullet -m py.test

env:
- PUSHBULLET_API_KEY=RrFnc1xaeQXnRrr2auoGA1e8pQ8MWmMF
