language: python
python:
- '3.5'
- '3.6'
- '3.7'
dist: xenial
sudo: true

before_installb :
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
- pip install .
- pip install coveralls
- pip install cryptography
- pip install requests
- pip install aiohttp
- pip install tqdm
- pip install python-magic

script: coverage run --source pushbullet -m py.test

env:
- PUSHBULLET_API_KEY=RrFnc1xaeQXnRrr2auoGA1e8pQ8MWmMF
#deploy:
#  provider: pypi
#  user: rharder
#  on:
#    tags: true
#    all_branches: true
#    python: '3.5'
#  distributions: sdist bdist_wheel
#  password:
#    secure: AF3VwPWZS4wDEuwhixbYJyF5jgWccAusPOq4ZdVOGzOmxAnc4DSuEr3sx6Z9HC3Svnw6nncbwx7nCCfrhX9va68xKiyNzkwa2jWnHWWKiYbGIY5oOsy728ElUA3cBg3fJWQy/+5wWdoS4a21jYw1MtqgVmMgEV3V3MvAy5nz98A=
#after_success:
#  coveralls
